version: '3'
services:

  ai.computer_vision:
    container_name: ai.computer_vision
    build: ./backend/ai_computer_vision
    volumes:
      - ./backend/ai_computer_vision/src:/usr/src/app
    command: sh -c " npm install && npm start "
    env_file:
      - .env


  storage.minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./volumes/storages/minio:/data
    env_file:
      - .env
    command: server --console-address :9009 /data

  api.getway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  api.minio.upload:
    build: backend/minio_storage
    volumes:
      - ./backend/minio_storage/src:/usr/src/app
    command: sh -c " npm install && npm start "
    container_name: api.minio.upload
    env_file:
      - .env

  api.azure.upload:
    build: backend/azure_storage
    volumes:
      - ./backend/azure_storage/src:/usr/src/app
    command: sh -c " npm install && npm start "
    container_name: api.azure.upload
    env_file:
      - .env


  notifications.router:
    container_name: notifications.router
    build: ./notifications/notification_router
    volumes:
      - ./notifications/notification_router/src:/usr/src/app
    command: sh -c " npm install && npm start "
    env_file:
      - .env

  notifications.email:
    container_name: notifications.email
    build: ./notifications/email
    volumes:
      - ./notifications/email/src:/usr/src/app
    command: sh -c " npm install && npm start "
    env_file:
      - .env


  websocket:
    build: ./notifications/websocket
    volumes:
      - ./notifications/websocket/src:/usr/src/app
    command: sh -c " npm install && npm start "
    container_name: websocket
    environment:
      - SERVER_NAME=WebSocket
      - SERVER_PORT=80
    env_file:
      - .env

  redis.sockets:
    image: 'redis:alpine'
    volumes:
      - './volumes/db/redis/sockets:/data'

  rabbit.mq:
    image: rabbitmq:3.12.0-management-alpine
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
