version: '3'
services:

  ai.natural:
    build: ai/naturalnode
    volumes:
      - ./ai/naturalnode/src:/usr/src/app
    command: sh -c " npm install && npm start "
    container_name: ai.natural
    env_file:
      - .env

  api.tickets:
    build: backend/tickets
    volumes:
      - ./backend/tickets/src:/usr/src/app
    command: sh -c " npm install && npm start "
    container_name: api.tickets
    env_file:
      - .env

  api.getway:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - websocket
      - api.tickets

  notifications.router:
    container_name: notifications.router
    build: ./notifications/notification_router
    volumes:
      - ./notifications/notification_router/src:/usr/src/app
    command: sh -c " npm install && npm start "
    env_file:
      - .env

  notifications.email:
    container_name: notifications.email
    build: ./notifications/email
    volumes:
      - ./notifications/email/src:/usr/src/app
    command: sh -c " npm install && npm start "
    env_file:
      - .env

  websocket:
    build: ./notifications/websocket
    volumes:
      - ./notifications/websocket/src:/usr/src/app
    command: sh -c " npm install && npm start "
    container_name: websocket
    environment:
      - SERVER_NAME=WebSocket
      - SERVER_PORT=80
    env_file:
      - .env

  redis.sockets:
    image: 'redis:alpine'
    volumes:
      - './volumes/db/redis/sockets:/data'

  front.public:
    build: ./frontend/public
    volumes:
      - ./frontend/public:/usr/src/app
    command: sh -c " npm install && npm start "

  front.admin:
    build: ./frontend/admin
    volumes:
      - ./frontend/admin:/usr/src/app
    command: sh -c " npm install && npm start "

  rabbit.mq:
    image: rabbitmq:3.12.0-management-alpine
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
